
# cargo-vet audits file

[[audits.actix-http]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "3.11.1 -> 3.11.2"

[[audits.addr2line]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.24.2 -> 0.25.1"

[[audits.backtrace]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.3.75 -> 0.3.76"

[[audits.bitflags]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "2.9.4 -> 2.10.0"

[[audits.cc]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.2.37 -> 1.2.39"

[[audits.cc]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.2.39 -> 1.2.40"

[[audits.cc]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.2.40 -> 1.2.41"

[[audits.cc]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.2.41 -> 1.2.43"

[[audits.cfg-if]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.0.3 -> 1.0.4"

[[audits.config]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.15.16 -> 0.15.18"

[[audits.deranged]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.5.3 -> 0.5.4"

[[audits.deranged]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.5.4 -> 0.5.5"

[[audits.find-msvc-tools]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.1.1 -> 0.1.2"

[[audits.find-msvc-tools]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.1.2 -> 0.1.3"

[[audits.find-msvc-tools]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.1.3 -> 0.1.4"

[[audits.flate2]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.1.4 -> 1.1.5"

[[audits.generic-array]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.14.7 -> 0.14.9"

[[audits.getrandom]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.3.3 -> 0.3.4"

[[audits.gimli]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.32.0 -> 0.32.3"

[[audits.home]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.5.11 -> 0.5.12"

[[audits.indexmap]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "2.11.4 -> 2.12.0"

[[audits.js-sys]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.3.80 -> 0.3.81"

[[audits.libc]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.2.175 -> 0.2.176"

[[audits.libc]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.2.176 -> 0.2.177"

[[audits.lock_api]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.4.13 -> 0.4.14"

[[audits.memchr]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "2.7.5 -> 2.7.6"

[[audits.mio]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.0.4 -> 1.1.0"

[[audits.nu-ansi-term]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.50.1 -> 0.50.3"

[[audits.object]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.36.7 -> 0.36.5"

[[audits.openssl]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.10.73 -> 0.10.74"

[[audits.openssl-sys]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.9.109 -> 0.9.110"

[[audits.parking_lot]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.12.4 -> 0.12.5"

[[audits.parking_lot_core]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.9.11 -> 0.9.12"

[[audits.pest]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "2.8.2 -> 2.8.3"

[[audits.pest_derive]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "2.8.2 -> 2.8.3"

[[audits.pest_generator]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "2.8.2 -> 2.8.3"

[[audits.pest_meta]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "2.8.2 -> 2.8.3"

[[audits.redox_syscall]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.5.17 -> 0.5.18"

[[audits.regex]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.11.2 -> 1.11.3"

[[audits.regex]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.11.3 -> 1.12.2"

[[audits.regex-automata]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.4.10 -> 0.4.11"

[[audits.regex-automata]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.4.11 -> 0.4.13"

[[audits.regex-lite]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.1.7 -> 0.1.8"

[[audits.regex-syntax]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.8.6 -> 0.8.8"

[[audits.reqwest]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.12.23 -> 0.12.24"

[[audits.rustls]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.23.31 -> 0.23.32"

[[audits.rustls]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.23.32 -> 0.23.33"

[[audits.rustls]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.23.33 -> 0.23.34"

[[audits.rustls-webpki]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.103.6 -> 0.103.7"

[[audits.serde_spanned]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.0.2 -> 1.0.3"

[[audits.socket2]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.6.0 -> 0.6.1"

[[audits.stable_deref_trait]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.2.0 -> 1.2.1"

[[audits.tempfile]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "3.22.0 -> 3.23.0"

[[audits.time]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.3.43 -> 0.3.44"

[[audits.tokio]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.47.1 -> 1.48.0"

[[audits.tokio-macros]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "2.5.0 -> 2.6.0"

[[audits.tokio-rustls]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.26.3 -> 0.26.4"

[[audits.toml]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.9.7 -> 0.9.8"

[[audits.toml_datetime]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.7.2 -> 0.7.3"

[[audits.toml_parser]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.0.3 -> 1.0.4"

[[audits.typenum]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.18.0 -> 1.19.0"

[[audits.wasm-bindgen]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.2.103 -> 0.2.104"

[[audits.wasm-bindgen-backend]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.2.103 -> 0.2.104"

[[audits.wasm-bindgen-futures]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.4.53 -> 0.4.54"

[[audits.wasm-bindgen-macro]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.2.103 -> 0.2.104"

[[audits.wasm-bindgen-macro-support]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.2.103 -> 0.2.104"

[[audits.wasm-bindgen-shared]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.2.103 -> 0.2.104"

[[audits.web-sys]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.3.80 -> 0.3.81"

[[audits.webpki-roots]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.0.2 -> 1.0.3"

[[audits.windows-core]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.62.1 -> 0.62.2"

[[audits.windows-implement]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.60.0 -> 0.60.1"

[[audits.windows-implement]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.60.1 -> 0.60.2"

[[audits.windows-interface]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.59.1 -> 0.59.2"

[[audits.windows-interface]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.59.2 -> 0.59.3"

[[audits.windows-link]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.2.0 -> 0.2.1"

[[audits.windows-result]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.4.0 -> 0.4.1"

[[audits.windows-strings]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.5.0 -> 0.5.1"

[[audits.windows-sys]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.61.0 -> 0.60.2"

[[audits.windows-sys]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.61.0 -> 0.61.1"

[[audits.windows-sys]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.61.1 -> 0.61.2"

[[audits.windows-targets]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.52.6 -> 0.53.5"

[[audits.windows_aarch64_gnullvm]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.52.6 -> 0.53.1"

[[audits.windows_aarch64_msvc]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.52.6 -> 0.53.1"

[[audits.windows_i686_gnu]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.52.6 -> 0.53.1"

[[audits.windows_i686_gnullvm]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.52.6 -> 0.53.1"

[[audits.windows_i686_msvc]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.52.6 -> 0.53.1"

[[audits.windows_x86_64_gnu]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.52.6 -> 0.53.1"

[[audits.windows_x86_64_gnullvm]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.52.6 -> 0.53.1"

[[audits.windows_x86_64_msvc]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.52.6 -> 0.53.1"

[[audits.zeroize]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.8.1 -> 1.8.2"

[[trusted.async-trait]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-07-23"
end = "2026-09-30"

[[trusted.erased-serde]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2020-01-06"
end = "2026-09-30"

[[trusted.itoa]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-05-02"
end = "2026-09-30"

[[trusted.proc-macro2]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-23"
end = "2026-09-30"

[[trusted.quote]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-09"
end = "2026-09-30"

[[trusted.rustversion]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-07-08"
end = "2026-09-30"

[[trusted.ryu]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-05-02"
end = "2026-09-30"

[[trusted.serde]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2026-09-30"

[[trusted.serde-untagged]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2023-08-27"
end = "2026-09-30"

[[trusted.serde_core]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2025-09-13"
end = "2026-09-30"

[[trusted.serde_derive]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2026-09-30"

[[trusted.serde_json]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-02-28"
end = "2026-09-30"

[[trusted.syn]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2026-09-30"

[[trusted.thiserror]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2026-09-30"

[[trusted.thiserror-impl]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2026-09-30"

[[trusted.typeid]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2024-05-13"
end = "2026-09-30"

[[trusted.unicode-ident]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2021-10-02"
end = "2026-09-30"
