
# cargo-vet audits file

[[audits.addr2line]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.24.2 -> 0.25.1"

[[audits.backtrace]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.3.75 -> 0.3.76"

[[audits.cc]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.2.37 -> 1.2.39"

[[audits.cc]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.2.39 -> 1.2.40"

[[audits.config]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.15.16 -> 0.15.18"

[[audits.deranged]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.5.3 -> 0.5.4"

[[audits.find-msvc-tools]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.1.1 -> 0.1.2"

[[audits.find-msvc-tools]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.1.2 -> 0.1.3"

[[audits.gimli]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.32.0 -> 0.32.3"

[[audits.js-sys]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.3.80 -> 0.3.81"

[[audits.libc]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.2.175 -> 0.2.176"

[[audits.lock_api]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.4.13 -> 0.4.14"

[[audits.memchr]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "2.7.5 -> 2.7.6"

[[audits.object]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.36.7 -> 0.36.5"

[[audits.parking_lot]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.12.4 -> 0.12.5"

[[audits.parking_lot_core]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.9.11 -> 0.9.12"

[[audits.pest]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "2.8.2 -> 2.8.3"

[[audits.pest_derive]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "2.8.2 -> 2.8.3"

[[audits.pest_generator]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "2.8.2 -> 2.8.3"

[[audits.pest_meta]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "2.8.2 -> 2.8.3"

[[audits.regex]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.11.2 -> 1.11.3"

[[audits.regex-automata]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.4.10 -> 0.4.11"

[[audits.rustls]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.23.31 -> 0.23.32"

[[audits.rustls-webpki]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.103.6 -> 0.103.7"

[[audits.tempfile]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "3.22.0 -> 3.23.0"

[[audits.time]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.3.43 -> 0.3.44"

[[audits.tokio-rustls]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.26.3 -> 0.26.4"

[[audits.typenum]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.18.0 -> 1.19.0"

[[audits.wasm-bindgen]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.2.103 -> 0.2.104"

[[audits.wasm-bindgen-backend]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.2.103 -> 0.2.104"

[[audits.wasm-bindgen-futures]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.4.53 -> 0.4.54"

[[audits.wasm-bindgen-macro]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.2.103 -> 0.2.104"

[[audits.wasm-bindgen-macro-support]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.2.103 -> 0.2.104"

[[audits.wasm-bindgen-shared]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.2.103 -> 0.2.104"

[[audits.web-sys]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.3.80 -> 0.3.81"

[[audits.windows-implement]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.60.0 -> 0.60.1"

[[audits.windows-interface]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.59.1 -> 0.59.2"

[[audits.windows-sys]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "0.61.0 -> 0.61.1"

[[audits.zeroize]]
who = "Reinis Danne <rei4dan@gmail.com>"
criteria = "safe-to-deploy"
delta = "1.8.1 -> 1.8.2"

[[trusted.async-trait]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-07-23"
end = "2026-09-30"

[[trusted.erased-serde]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2020-01-06"
end = "2026-09-30"

[[trusted.itoa]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-05-02"
end = "2026-09-30"

[[trusted.proc-macro2]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-23"
end = "2026-09-30"

[[trusted.quote]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-09"
end = "2026-09-30"

[[trusted.rustversion]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-07-08"
end = "2026-09-30"

[[trusted.ryu]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-05-02"
end = "2026-09-30"

[[trusted.serde]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2026-09-30"

[[trusted.serde-untagged]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2023-08-27"
end = "2026-09-30"

[[trusted.serde_core]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2025-09-13"
end = "2026-09-30"

[[trusted.serde_derive]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2026-09-30"

[[trusted.serde_json]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-02-28"
end = "2026-09-30"

[[trusted.syn]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2026-09-30"

[[trusted.thiserror]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2026-09-30"

[[trusted.thiserror-impl]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2026-09-30"

[[trusted.typeid]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2024-05-13"
end = "2026-09-30"

[[trusted.unicode-ident]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2021-10-02"
end = "2026-09-30"
