
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.actix-codec]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.actix-http]]
version = "3.11.1"
criteria = "safe-to-deploy"

[[exemptions.actix-macros]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.actix-router]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.actix-rt]]
version = "2.11.0"
criteria = "safe-to-deploy"

[[exemptions.actix-server]]
version = "2.6.0"
criteria = "safe-to-deploy"

[[exemptions.actix-service]]
version = "2.0.3"
criteria = "safe-to-deploy"

[[exemptions.actix-utils]]
version = "3.0.1"
criteria = "safe-to-deploy"

[[exemptions.actix-web]]
version = "4.11.0"
criteria = "safe-to-deploy"

[[exemptions.actix-web-codegen]]
version = "4.3.0"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.8.12"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.alloc-no-stdlib]]
version = "2.0.4"
criteria = "safe-to-deploy"

[[exemptions.alloc-stdlib]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.atoi]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.base64ct]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.brotli]]
version = "8.0.2"
criteria = "safe-to-deploy"

[[exemptions.brotli-decompressor]]
version = "5.0.0"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.10.1"
criteria = "safe-to-deploy"

[[exemptions.bytestring]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.2.37"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.42"
criteria = "safe-to-deploy"

[[exemptions.concurrent-queue]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.config]]
version = "0.15.16"
criteria = "safe-to-deploy"

[[exemptions.const-oid]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.const-random]]
version = "0.1.18"
criteria = "safe-to-deploy"

[[exemptions.const-random-macro]]
version = "0.1.16"
criteria = "safe-to-deploy"

[[exemptions.convert_case]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.cookie]]
version = "0.16.2"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.crc]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.crc-catalog]]
version = "2.4.0"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-queue]]
version = "0.3.12"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.21"
criteria = "safe-to-deploy"

[[exemptions.crunchy]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.der]]
version = "0.7.10"
criteria = "safe-to-deploy"

[[exemptions.deranged]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.derive_more]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.derive_more-impl]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.dlv-list]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.dotenvy]]
version = "0.15.7"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.3.14"
criteria = "safe-to-deploy"

[[exemptions.etcetera]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.event-listener]]
version = "5.4.1"
criteria = "safe-to-deploy"

[[exemptions.find-msvc-tools]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.flume]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.futures-intrusive]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.gethostname]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.h2]]
version = "0.3.27"
criteria = "safe-to-deploy"

[[exemptions.h2]]
version = "0.4.12"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.14.5"
criteria = "safe-to-deploy"

[[exemptions.hashlink]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.hkdf]]
version = "0.12.4"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "0.2.12"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "1.3.1"
criteria = "safe-to-deploy"

[[exemptions.http-body]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.http-body-util]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.httparse]]
version = "1.10.1"
criteria = "safe-to-deploy"

[[exemptions.hyper]]
version = "1.7.0"
criteria = "safe-to-deploy"

[[exemptions.hyper-rustls]]
version = "0.27.7"
criteria = "safe-to-deploy"

[[exemptions.hyper-tls]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.hyper-util]]
version = "0.1.17"
criteria = "safe-to-deploy"

[[exemptions.idna]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.impl-more]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.11.0"
criteria = "safe-to-deploy"

[[exemptions.iri-string]]
version = "0.7.8"
criteria = "safe-to-deploy"

[[exemptions.jobserver]]
version = "0.1.34"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.80"
criteria = "safe-to-deploy"

[[exemptions.json5]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.language-tags]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.175"
criteria = "safe-to-deploy"

[[exemptions.libm]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.libredox]]
version = "0.1.10"
criteria = "safe-to-deploy"

[[exemptions.libsqlite3-sys]]
version = "0.30.1"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.local-channel]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.local-waker]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.13"
criteria = "safe-to-deploy"

[[exemptions.md-5]]
version = "0.10.6"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.5"
criteria = "safe-to-deploy"

[[exemptions.mime]]
version = "0.3.17"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.mutually_exclusive_features]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.num-bigint-dig]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.openssl]]
version = "0.10.73"
criteria = "safe-to-deploy"

[[exemptions.openssl-probe]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.openssl-sys]]
version = "0.9.109"
criteria = "safe-to-deploy"

[[exemptions.ordered-float]]
version = "2.10.1"
criteria = "safe-to-deploy"

[[exemptions.ordered-multimap]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.parking]]
version = "2.2.1"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.12.4"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.11"
criteria = "safe-to-deploy"

[[exemptions.pathdiff]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.pem-rfc7468]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.pest]]
version = "2.8.2"
criteria = "safe-to-deploy"

[[exemptions.pest_derive]]
version = "2.8.2"
criteria = "safe-to-deploy"

[[exemptions.pest_generator]]
version = "2.8.2"
criteria = "safe-to-deploy"

[[exemptions.pest_meta]]
version = "2.8.2"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.pkcs1]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.pkcs8]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.pkg-config]]
version = "0.3.32"
criteria = "safe-to-deploy"

[[exemptions.potential_utf]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.21"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "5.3.0"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.5.17"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.11.2"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.10"
criteria = "safe-to-deploy"

[[exemptions.regex-lite]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.reqwest]]
version = "0.12.23"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.14"
criteria = "safe-to-deploy"

[[exemptions.ron]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.rsa]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.rust-ini]]
version = "0.21.3"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "1.1.2"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.23.31"
criteria = "safe-to-deploy"

[[exemptions.rustls-pki-types]]
version = "1.12.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.103.6"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.28"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.secrecy]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "2.11.1"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.15.0"
criteria = "safe-to-deploy"

[[exemptions.serde-aux]]
version = "4.7.0"
criteria = "safe-to-deploy"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.6"
criteria = "safe-to-deploy"

[[exemptions.signature]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.11"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.5.10"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.spki]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.sqlx]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.sqlx-core]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.sqlx-macros]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.sqlx-macros-core]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.sqlx-mysql]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.sqlx-postgres]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.sqlx-sqlite]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.stringprep]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.system-configuration]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.system-configuration-sys]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.22.0"
criteria = "safe-to-deploy"

[[exemptions.thread_local]]
version = "1.1.9"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.43"
criteria = "safe-to-deploy"

[[exemptions.time-core]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.24"
criteria = "safe-to-deploy"

[[exemptions.tiny-keccak]]
version = "2.0.2"
criteria = "safe-to-deploy"

[[exemptions.tinyvec]]
version = "1.10.0"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.47.1"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.26.3"
criteria = "safe-to-deploy"

[[exemptions.tokio-stream]]
version = "0.1.17"
criteria = "safe-to-deploy"

[[exemptions.tokio-util]]
version = "0.7.16"
criteria = "safe-to-deploy"

[[exemptions.toml]]
version = "0.9.7"
criteria = "safe-to-deploy"

[[exemptions.toml_datetime]]
version = "0.7.2"
criteria = "safe-to-deploy"

[[exemptions.toml_parser]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.tower]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.tower-http]]
version = "0.6.6"
criteria = "safe-to-deploy"

[[exemptions.tower-layer]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.tracing-actix-web]]
version = "0.7.19"
criteria = "safe-to-deploy"

[[exemptions.tracing-bunyan-formatter]]
version = "0.3.10"
criteria = "safe-to-deploy"

[[exemptions.tracing-log]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.try-lock]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.18.0"
criteria = "safe-to-deploy"

[[exemptions.ucd-trie]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.unicode-properties]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.uuid]]
version = "1.18.1"
criteria = "safe-to-deploy"

[[exemptions.valuable]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.want]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.1+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasite]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.103"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-futures]]
version = "0.4.53"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.103"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.103"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.103"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.80"
criteria = "safe-to-deploy"

[[exemptions.webpki-roots]]
version = "0.26.11"
criteria = "safe-to-deploy"

[[exemptions.webpki-roots]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.whoami]]
version = "1.6.1"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows-core]]
version = "0.62.1"
criteria = "safe-to-deploy"

[[exemptions.windows-implement]]
version = "0.60.0"
criteria = "safe-to-deploy"

[[exemptions.windows-interface]]
version = "0.59.1"
criteria = "safe-to-deploy"

[[exemptions.windows-registry]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.windows-result]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows-strings]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.61.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.winnow]]
version = "0.7.13"
criteria = "safe-to-deploy"

[[exemptions.yaml-rust2]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.27"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.27"
criteria = "safe-to-deploy"

[[exemptions.zstd]]
version = "0.13.3"
criteria = "safe-to-deploy"

[[exemptions.zstd-safe]]
version = "7.2.4"
criteria = "safe-to-deploy"

[[exemptions.zstd-sys]]
version = "2.0.16+zstd.1.5.7"
criteria = "safe-to-deploy"
